---
# tasks file for nginx
- name: install tools
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - python-httplib2
    
- name: install nginx
  apt: name=nginx state=present update_cache=yes

- name: configure nginx sites
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{ item.key }} mode=0644
  with_dict: "{{ sites }}"
  notify: restart nginx

- name: get active sites from /etc/nginx/sites-enabled
  #use ls -1, not ls -l
  shell: ls -1 /etc/nginx/sites-enabled
  register: active

- name: deactivate any nginx site != to the site we want
  file: path=/etc/nginx/sites-enabled/{{ item }} state=absent
  with_items: "{{ active.stdout_lines }}"
  when: item not in sites
  notify: restart nginx

- name: activate demo nginx sites bro
  file: src=/etc/nginx/sites-available/{{ item.key }} dest=/etc/nginx/sites-enabled/{{ item.key }} state=link
  with_dict: "{{ sites }}"
  notify: restart nginx

- name: ensure nginx started
  service: name=nginx state=started enabled=yes