---
- hosts: databases
  become: true
  roles:
    # use a list injection here to override the default values in ./defaults/main.yml
    - role: mysql
      db_user_name: "{{ db_user }}"
      db_user_pass: "{{ db_pass }}"
      db_user_host: '%'