---

# bring stack down; stop nginx and apache

- hosts: loadbalancers
  become: true
  tasks:
      - service: name=nginx state=stopped
      - wait_for: port=80 state=drained

- hosts: webservers
  become: true
  tasks:
      - service: name=apache2 state=stopped
      - wait_for: port=80 state=drained

# restart mysql database server

- hosts: databases
  become: true
  tasks:
      - service: name=mysql state=restarted
      - wait_for: host={{ ansible_enp0s8.ipv4.address }} port=3306 state=started

# bring stack back online

- hosts: webservers
  become: true
  tasks:
      - service: name=apache2 state=restarted
      - wait_for: port=80 state=started

- hosts: loadbalancers
  become: true
  tasks:
      - service: name=nginx state=started
      - wait_for: port=80 state=started