---
# tasks file for apache2
- name: install web components
  apt:  name={{item}} state=present 
  with_items:
  - apache2
  - libapache2-mod-wsgi
  tags: [ 'packages' ]

- name: ensure mod_wsgi apache2 module is enabled=yes
  apache2_module: state=present name=wsgi
  notify: restart apache2
  tags: [ 'configure' ]

- name: de-activate default apache2 website (000-default.conf)
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify: restart apache2
  tags: [ 'configure' ]

- name: ensure that apache2 service is started
  service: name=apache2 state=started enabled=yes
  tags: [ 'service' ]